"""Lock the Cisco completeness ARTIFACT against the anti-circularity contract.

config/coverage/cisco_transceivers_completeness.yaml is a VERIFIED reconcile of the Cisco
transceiver harvest against the union of independent official enumerations (today: the TMG
optics-to-device compatibility matrix; EOL/EOS, ordering-guide and GPL snapshots fold in as
gathered). These tests pin the contract the mission demands:

  * the verdict is COMPUTED from real lists, never a hand-set flag — captured/gaps/gone must
    account for the whole universe exactly;
  * "complete" can NEVER be claimed while real gaps remain (the decisive guard against a silent
    or circular "done");
  * the universe is non-empty and built from at least one populated independent source (an empty
    universe is never vacuously complete);
  * every gap is recorded explicitly so nothing is silently dropped.

The artifact is regenerated by _scratch/reconcile_cisco_completeness.py; these tests also re-run
the pure reconciler over the same inputs to prove the file on disk matches the computed truth.
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

from lib.completeness import reconcile_brand

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "config" / "coverage" / "cisco_transceivers_completeness.yaml"
CONTENT = ROOT / "stage3_content" / "Cisco_content.json"
DISP = ROOT / "config" / "coverage" / "cisco_transceivers_disposition.yaml"
UNION_TRIAGE = ROOT / "config" / "coverage" / "cisco_transceivers_union_triage.yaml"
TMG = ROOT / "config" / "coverage" / "enumerations" / "cisco_tmg_matrix.txt"


def _artifact() -> dict:
    return yaml.safe_load(ART.read_text(encoding="utf-8"))


def _harvested() -> set[str]:
    pns = set(json.loads(CONTENT.read_text(encoding="utf-8")).keys())
    for disp_path in (DISP, UNION_TRIAGE):
        if not disp_path.exists():
            continue
        disp = yaml.safe_load(disp_path.read_text(encoding="utf-8"))
        for bucket in ("add", "exclude_not_transceiver"):
            for e in (disp.get(bucket) or []):
                pns.add(e["pn"])
    return pns


# ---- the artifact exists and accounts for the whole universe exactly ------------------

def test_artifact_counts_account_for_whole_universe():
    a = _artifact()
    # captured + gaps + confirmed_gone == universe  (nothing unaccounted, nothing double-counted)
    assert a["captured_count"] + a["gap_count"] + a["confirmed_gone_count"] == a["universe_total"]
    assert a["gap_count"] == len(a["gaps"])
    assert a["confirmed_gone_count"] == len(a["confirmed_gone"])
    assert a["extra_count"] == len(a["extra"])


def test_universe_is_nonempty_and_from_a_populated_source():
    a = _artifact()
    assert a["universe_total"] > 0
    assert a["populated_sources"] >= 1
    assert any(s["populated"] for s in a["per_source"])


# ---- THE anti-circularity guard: never "complete" while gaps remain -------------------

def test_complete_is_false_while_gaps_remain():
    a = _artifact()
    if a["gap_count"] > 0:
        assert a["complete"] is False, "completeness was claimed while real gaps remain"
    # and the verdict is the computed rule, never an arbitrary flag
    computed = a["populated_sources"] > 0 and a["gap_count"] == 0
    assert a["complete"] == computed


def test_every_gap_is_recorded_explicitly():
    a = _artifact()
    assert sorted(a["gaps"]) == a["gaps"], "gaps must be a sorted, explicit list"
    # a gap is a real PN string, never blank
    assert all(isinstance(g, str) and g.strip() for g in a["gaps"])


# ---- the file on disk matches the pure reconciler over the same inputs ----------------

def test_artifact_matches_recomputed_reconcile():
    rep = reconcile_brand("transceivers", "Cisco", _harvested(), root=ROOT)
    a = _artifact()
    assert rep.to_doc()["universe_total"] == a["universe_total"]
    assert rep.to_doc()["captured_count"] == a["captured_count"]
    assert sorted(rep.gaps) == a["gaps"]
    assert rep.complete == a["complete"]


def test_tmg_snapshot_has_no_placeholder_wildcards():
    """The TMG snapshot must hold only real PNs — family-template wildcards (XX+) are non-PN
    stand-ins and would be phantom permanent gaps that falsely block 'complete' forever."""
    pns = [ln.split("#", 1)[0].strip() for ln in TMG.read_text(encoding="utf-8").splitlines()
           if ln.strip() and not ln.startswith("#")]
    assert pns, "expected gathered TMG PIDs"
    assert all("XX" not in p.upper() for p in pns), "placeholder wildcard leaked into the universe"


# ---- the union triage: every PN accounted, every exclusion grounded, nothing guessed ----

def _union_triage() -> dict:
    return yaml.safe_load(UNION_TRIAGE.read_text(encoding="utf-8"))


def test_union_triage_leaves_nothing_ungrounded():
    """The closure rule: every completeness-union gap is resolved to a real transceiver (ADD) or a
    grounded non-transceiver (EXCLUDE). A PN that could NOT be grounded is FLAGGED, never excluded —
    so an empty flag list is the proof nothing was guessed away."""
    t = _union_triage()
    assert t["flag_ungrounded"] == [] or t["flag_ungrounded"] is None, \
        "ungrounded PNs remain — they must be grounded, never silently dropped or excluded"
    assert t["counts"]["FLAG_UNGROUNDED"] == 0


def test_union_triage_exclusions_are_grounded_non_transceivers():
    """The ONLY permitted exclusion is a genuine non-transceiver, and the reason must quote the
    part's own Cisco description (cable / converter / mux-demux / OADM / amplifier)."""
    t = _union_triage()
    for e in (t.get("exclude_not_transceiver") or []):
        assert e["description"].strip(), f"{e['pn']} excluded with no grounding description"
        assert e["pn"] in (q for q in [e["pn"]])  # pn present
        assert any(k in e["reason"].lower()
                   for k in ("cable", "converter", "adapter", "bracket", "tray",
                             "mux", "demux", "oadm", "amplifier")), \
            f"{e['pn']} exclusion reason is not a recognised non-transceiver: {e['reason']}"


def test_cisco_verdict_is_complete_and_consistent():
    """With the union fully triaged, Cisco transceivers reconcile to COMPLETE — captured == universe,
    zero gaps — and the verdict is the computed rule, not a hand-set flag."""
    a = _artifact()
    assert a["gap_count"] == 0
    assert a["captured_count"] == a["universe_total"]
    assert a["complete"] is True
    rep = reconcile_brand("transceivers", "Cisco", _harvested(), root=ROOT)
    assert rep.complete is True and not rep.gaps
