# -*- coding: utf-8 -*-
"""COVERAGE RECONCILER — the permanent completeness gate.

Diffs a catalog manifest (the in-scope denominator) against what is actually emitted, and writes a
coverage report: per-family expected-vs-built + the exact MISSING PN list, overall %, and a
prioritized missing backlog. Nothing is "complete" until built == in-scope manifest; explicitly
deferred items are listed, never silently dropped.

Usage:
  python lib/coverage_reconcile.py switches      # manifest catalog_manifest/cisco_switches.csv vs output/switches/
  python lib/coverage_reconcile.py transceivers  # (BUILD 3) once a transceiver manifest exists
Any "category complete" claim must cite the report this produces.
"""
from __future__ import annotations
import csv, re, sys
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]


def _built_switch_pns():
    pns = {}
    sw = ROOT/"output"/"switches"
    if not sw.exists():
        return pns
    for d in sw.iterdir():
        if not d.is_dir():
            continue
        mf = d/f"Hexwaren_{d.name}_Switches_Main.csv"
        if mf.exists():
            for r in csv.reader(open(mf, encoding="utf-8-sig"), delimiter=";"):
                if r and r[0] != "Artikelnummer":
                    pns[r[0]] = d.name
    return pns


def reconcile_switches(manifest_path: Path, out_path: Path) -> dict:
    rows = list(csv.DictReader(open(manifest_path, encoding="utf-8-sig")))
    built = _built_switch_pns()
    fams = defaultdict(lambda: {"prio": 9, "exp": 0, "built": 0, "missing_pns": [], "tbd": 0, "note": ""})
    for r in rows:
        fam = r["Family"]; f = fams[fam]
        f["prio"] = min(f["prio"], int(r["Priority"]))
        pn = r["Model-PN"]
        m = re.search(r"family-level — (\d+) models", pn)
        if m:                                   # family-level row (count only, PNs TBD)
            f["exp"] += int(m.group(1)); f["tbd"] += int(m.group(1)); f["note"] = r["Notes"]
        else:                                   # model-level row
            f["exp"] += 1
            if r["Status"] == "built" or pn in built:
                f["built"] += 1
            else:
                f["missing_pns"].append(pn)

    tot_exp = sum(f["exp"] for f in fams.values())
    tot_built = sum(f["built"] for f in fams.values())
    tot_fam = len(fams)
    built_fam = sum(1 for f in fams.values() if f["built"] and f["built"] == f["exp"])
    partial_fam = sum(1 for f in fams.values() if 0 < f["built"] < f["exp"])

    L = []
    L.append("# Cisco Switch — Catalogue Coverage Report\n")
    L.append(f"_Generated by `lib/coverage_reconcile.py` from `{manifest_path.relative_to(ROOT)}` vs `output/switches/`._\n")
    L.append("**Nothing is \"complete\" until built == in-scope manifest.** EoS families are in scope "
             "(Hexwaren sells EoL new-sealed) — flagged, never dropped.\n")
    L.append("## Headline\n")
    L.append(f"- **Families in scope:** {tot_fam}  ·  fully built: **{built_fam}**  ·  partial: **{partial_fam}**  ·  not started: **{tot_fam-built_fam-partial_fam}**")
    L.append(f"- **In-scope models (incl. ~est for legacy):** ~{tot_exp}  ·  **built: {tot_built}**  ·  coverage: **{tot_built*100//tot_exp}%**")
    L.append(f"- Precisely-enumerated models (Catalyst-9000 + Nexus-9000): {sum(f['exp']-f['tbd'] for f in fams.values())} "
             f"({tot_built} built / {sum(len(f['missing_pns']) for f in fams.values())} missing)")
    L.append(f"- Family-level-only (counts est., per-model PNs TBD): ~{sum(f['tbd'] for f in fams.values())} models across "
             f"{sum(1 for f in fams.values() if f['tbd'])} families\n")

    L.append("## Family coverage table\n")
    L.append("| Family | Pri | Expected | Built | Missing | Coverage |")
    L.append("|---|:--:|--:|--:|--:|:--:|")
    for fam in sorted(fams, key=lambda k: (fams[k]["prio"], -fams[k]["exp"])):
        f = fams[fam]
        miss = f["exp"] - f["built"]
        cov = f"{f['built']*100//f['exp']}%" if f["exp"] else "—"
        tag = "✅" if miss == 0 else ("🟡" if f["built"] else "⬜")
        L.append(f"| {tag} {fam} | {f['prio']} | {f['exp']}{'~' if f['tbd'] else ''} | {f['built']} | {miss} | {cov} |")

    L.append("\n## Exact missing PNs — Catalyst-9000 / Nexus-9000 (precisely enumerated)\n")
    any_miss = False
    for fam in sorted(fams, key=lambda k: (fams[k]["prio"], k)):
        f = fams[fam]
        if f["missing_pns"]:
            any_miss = True
            L.append(f"- **{fam}** (P{f['prio']}, {len(f['missing_pns'])} missing): {', '.join(f['missing_pns'])}")
    if not any_miss:
        L.append("_(none — all enumerated models built)_")

    L.append("\n## Prioritized missing backlog (set priority here, then build)\n")
    for prio in (1, 2, 3, 4):
        fl = [fam for fam in fams if fams[fam]["prio"] == prio and fams[fam]["exp"] > fams[fam]["built"]]
        if not fl:
            continue
        L.append(f"\n### Priority {prio}")
        for fam in sorted(fl, key=lambda k: -(fams[k]["exp"]-fams[k]["built"])):
            f = fams[fam]; miss = f["exp"]-f["built"]
            extra = f" — {f['note']}" if f["tbd"] else (f" — PNs: {', '.join(f['missing_pns'])}" if f["missing_pns"] else "")
            L.append(f"- **{fam}**: {miss} model(s) missing{extra}")

    out_path.write_text("\n".join(L)+"\n", encoding="utf-8")
    return dict(families=tot_fam, models_exp=tot_exp, models_built=tot_built,
                enum_missing=sum(len(f["missing_pns"]) for f in fams.values()),
                tbd=sum(f["tbd"] for f in fams.values()))


def main():
    cat = sys.argv[1] if len(sys.argv) > 1 else "switches"
    if cat == "switches":
        mp = ROOT/"catalog_manifest"/"cisco_switches.csv"
        rep = ROOT/"coverage_report.md"
        print(reconcile_switches(mp, rep))
    elif cat == "transceivers":
        mp = ROOT/"catalog_manifest"/"cisco_transceivers.csv"
        if not mp.exists():
            print("BUILD 3 pending: no transceiver manifest yet at", mp.relative_to(ROOT),
                  "— assemble denominator from live JTL export + distributor catalogues first.")
            return
        print(reconcile_switches(mp, ROOT/"coverage_report_transceivers.md"))
    else:
        print("usage: coverage_reconcile.py [switches|transceivers]")


if __name__ == "__main__":
    main()
